id: ID4398095
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T06:03:13+00:00'
last_modified: '2022-06-08T08:55:45.014625+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24788
  title: ངའི་ཆུར་བ་སུས་ཁྱེར་སོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    846E:
      image_group_id: I1KG24790
      title: ''
      total_pages: 159
      order: 1
      base_file: 846E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
